### ISSUE TITLE
Version 2.1.1 not working

### ISSUE THREAD

**Issue by CMDR-Cometborne** [CMDR-Kiel42/EDMC_SpanshRouter#8]
After updating from 2.0, the plugin no longer works.  The EDMC logfile says:

loading plugin SpanshRouter from "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\SpanshRouter\load.py"
Traceback (most recent call last):
  File "plug.pyo", line 190, in load_plugins
  File "plug.pyo", line 91, in __init__
  File "C:\Users\ue\AppData\Local\EDMarketConnector\plugins\SpanshRouter\load.py", line 12, in <module>
ImportError: cannot import name SpanshUpdater

Looking at the .py files shows all of them except load.py seem to be using Unix EOL rather than Windows, and this seems to break things.

**Comment by CMDR-Cometborne** [comment]
Update after a debugging session: This was caused by another EDMC plugin (Hutton Helper) which also contained an updater.py file.  The current workaround is to rename updater.py to SpanshUpdater.py, and change the import line in load.py accordingly.

**Comment by CMDR-Kiel42** [comment]
That should be fixed in the release 2.1.2.

**Comment by CMDR-Cometborne** [comment]
This is indeed fixed by the new version, closing issue.
